### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by ciwanceylan** [giannisnik/segk#2]
Hi!

I'm doing research into network mining and node embeddings. I would like to use your SEGK algorithm as part of a benchmark suite for node embedding models.

However, I believe I am not legally entitled to use the code in this repo for any purpose since it is missing a licence.

Would you have the possibility to add a licence so that I can use your code and cite your paper? 

Best,
Ciwan

**Comment by giannisnik** [comment]
Hi @ciwanceylan 

Thank you for your interest in our work. I have added a license, so that you can add the algorithm in your package.
